### ISSUE TITLE
AttributeError: module 'discord' has no attribute 'Server'

### ISSUE THREAD

**Issue by Beehivenetwork** [boyroywax/python-tipbot-v2#1]
don't work

> Traceback (most recent call last):
>   File "bot.py", line 3, in <module>
>     from utils import output, parsing, checks, mysql_module, helpers
>   File "/root/sct-tip-bot/utils/checks.py", line 1, in <module>
>     from utils import parsing, mysql_module
>   File "/root/sct-tip-bot/utils/mysql_module.py", line 11, in <module>
>     class Mysql:
>   File "/root/sct-tip-bot/utils/mysql_module.py", line 24, in Mysql
>     class __Mysql:
>   File "/root/sct-tip-bot/utils/mysql_module.py", line 98, in __Mysql
>     def check_server(self, server: discord.Server):
> AttributeError: module 'discord' has no attribute 'Server'

**Comment by Beehivenetwork** [comment]
resolved with delete current discord.py
install branch async
